apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: generator
  name: generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: generator
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: generator
    spec:
      containers:
        - image: REGION_TEMPLATE_KEY.ocir.io/TENANCY_TEMPLATE_NAMESPACE/oci_multiplayer/generator:0.0.1
          name: generator
          # readinessProbe:
          #   tcpSocket:
          #     port: 3000
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          env:
          - name: NODE_ENV
            value: "production"
          volumeMounts:
          - name: config-volume
            mountPath: /usr/src/app/config
      volumes:
      - name: config-volume
        configMap:
          name: generator-env
      imagePullSecrets:
        - name: ocir-secret
